name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn lerna:bootstrap
      - run: yarn lerna:build
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn lerna:bootstrap
      - run: yarn lerna:build
      - run: yarn lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
